
package com.inflectra.spirateam.mylyn.core.internal.services.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationFaultMessage", targetNamespace = "http://schemas.datacontract.org/2004/07/Inflectra.SpiraTest.Web.Services.v5_0")
public class ISoapServiceIncidentUpdateValidationFaultMessageFaultFaultMessage
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -2294989131349408471L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidationFaultMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ISoapServiceIncidentUpdateValidationFaultMessageFaultFaultMessage(String message, ValidationFaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ISoapServiceIncidentUpdateValidationFaultMessageFaultFaultMessage(String message, ValidationFaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.inflectra.spirateam.mylyn.core.internal.services.soap.ValidationFaultMessage
     */
    public ValidationFaultMessage getFaultInfo() {
        return faultInfo;
    }

}
