
package com.inflectra.spirateam.mylyn.core.internal.services.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapService", targetNamespace = "http://www.inflectra.com/SpiraTest/Services/v5.0/", wsdlLocation = "file:/C:/Users/peter.geertsema/git/spira_eclipse/com.inflectra.spirateam.mylyn.core/src/com/inflectra/spirateam/mylyn/core/internal/services/SoapService50.wsdl")
public class SoapService
    extends Service
{

    private final static URL SOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICE_EXCEPTION;
    private final static QName SOAPSERVICE_QNAME = new QName("http://www.inflectra.com/SpiraTest/Services/v5.0/", "SoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/peter.geertsema/git/spira_eclipse/com.inflectra.spirateam.mylyn.core/src/com/inflectra/spirateam/mylyn/core/internal/services/SoapService50.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICE_WSDL_LOCATION = url;
        SOAPSERVICE_EXCEPTION = e;
    }

    public SoapService() {
        super(__getWsdlLocation(), SOAPSERVICE_QNAME);
    }

    public SoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICE_QNAME, features);
    }

    public SoapService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICE_QNAME);
    }

    public SoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICE_QNAME, features);
    }

    public SoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoapService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoapService")
    public ISoapService getBasicHttpBindingISoapService() {
        return super.getPort(new QName("http://www.inflectra.com/SpiraTest/Services/v5.0/", "BasicHttpBinding_ISoapService"), ISoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoapService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoapService")
    public ISoapService getBasicHttpBindingISoapService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.inflectra.com/SpiraTest/Services/v5.0/", "BasicHttpBinding_ISoapService"), ISoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICE_EXCEPTION;
        }
        return SOAPSERVICE_WSDL_LOCATION;
    }

}
